### PR TITLE
Simple PR to fix the REF pages black screen and provide additional input protection

### LINKED ISSUE #253: CJ4: FMS black screen in PERF approach
Hello, the FMS screen went black after I hit the "next" page in PERF Approach. I had the following: 

Wind: 250/6
Temp: 7º
QNH: 30.24

ENBO/25 IBVI2B BO710 DCT OSRUL RNAV Y ENSH/01

This happened a few miles before OSRUL when I was finishing the approach setup.

CJ4 0.4.1 and MSFS 1.9.5

Thank you!

### PR DESCRIPTION
**Pull request by cwburnett**
- [x] Added input filters on TAKEOFF REF and APPROACH REF pages / closes #253 
- [x] Fixed gross weight variable name

### CODE REVIEW

File: src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_PerfInitPage.js [hunk 1]
```diff
@@ -296,24 +313,24 @@ class CJ4_FMC_PerfInitPage {
...
+                CJ4_FMC_PerfInitPage.ShowPage14(fmc, arrRunwayOutput);
             }
             else {
                 fmc.showErrorMessage("INVALID");
             }
             };
         fmc.updateSideButtonActiveStatus();
     }
-    static ShowPage14(fmc) { //APPROACH REF Page 2
+    static ShowPage14(fmc, arrRunwayOutput = "XX") { //APPROACH REF Page 2
```
Comment (dga711) [inline src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_PerfInitPage.js:333]: it is not needed needed to carry over the runway from page 13 to page 14
just get it again in page 14
or extract it to a function

**Review by dga711 — APPROVED** [review]

**Review by mattnischan — APPROVED** [review]

File: src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_PerfInitPage.js (hunk 1 above)
Comment (cwburnett) [reply src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_PerfInitPage.js:333]: Well, it's about 15 lines of code to get the arrRunwayOutput ;-) that's why I didn't want to duplicate it on the next page, but I can... I'm not totally sure on the proper procedure to extract to a function outside the page...a quick lesson and I can probably do that easily.
