### PR TITLE
CJ4: FPLN fix update problems on modification

### LINKED ISSUE #636: [cj4-08] FLPN page 2 (legs) is not refreshing unless exec/prev/next are pressed
Discord:  Erich Convair#6521

Occurrence: systematic
FP: LFBA DCT PERIG UY156 FOUCO UT181 POI UT182 PEPAX/N0449F300 UT182 KEPER KEPE9W LFPG

Once on the FPLN page 2, the route or wp typed in the input area are not visually inserted in the via/to part. The screen only refresh if you press either exec or prev/next.

Sometime the WP is inserted correctly without refreshing manually.

How to reproduce:

Once the setting set accordingly, go to page 2

1 type: UY156 (appears on the pad)
2 press VIA --> pad cleared 
NO UY156 displayed under VIA

3 type FOUCO then press TO 
--> nothing appears under TO

4 Press either EXEC or PREV/NEXT make the leg appears correctly

---- 
Sometime anothe leg works as expected for the VIA part but inserting the TO failed to display until pressing EXEC / prev/next

I failed recording the screen to show what's happening.

### PR DESCRIPTION
**Pull request by dga711**
closes #636

### CODE REVIEW

File: src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_RoutePage.js [hunk 1]
```diff
@@ -147,6 +147,7 @@ class CJ4_FMC_RoutePage {
     }
 
     render() {
+        console.log("render");
```
Comment (mattnischan) [inline src/workingtitle-vcockpits-instruments-cj4/html_ui/Pages/VCockpit/Instruments/Airliners/CJ4/FMC/CJ4_FMC_RoutePage.js:150]: Left some console logs in these changes still.

**Review by mattnischan — APPROVED** [review]
